
const DB_COLLECTIONS = {
    SYNC_ORDER_REQUEST: 'sync-order-request'
}

const SYNC_ORDER_REQUEST_STATES = {
    INITIATED: 'INITIATED',
    SHOPIFY_ORDER_CREATED: 'SHOPIFY_ORDER_CREATED',
    SHOPIFY_ORDER_FAILED: 'SHOPIFY_ORDER_FAILED',
    SHOPIFY_PAYMENT_CREATED: 'SHOPIFY_PAYMENT_CREATED',
    ORDER_SYNC_COMPLETE: 'ORDER_SYNC_COMPLETE'
}

module.exports = {
    DB_COLLECTIONS,
    SYNC_ORDER_REQUEST_STATES
}